version: '3.4'

services:
  app:
    container_name: 'app-tcc'
    build: .
    ports:
      - '8082:8082'
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
    #   - "traefik.http.routers.whoami.entrypoints=web"