version: '3.4'

services:
  app:
    container_name: 'app-tcc'
    build: .
    ports:
      - '8082:8082'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app.rule=Host(`host`) && PathPrefix(`/api`)'
      - 'traefik.http.services.app.loadbalancer.server.port=8082'